// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkcuq1Sxpw9H4gniCQB07kdhpNi8BjpwU',
    appId: '1:7816793803:web:b77835a93fb2ad92c1954e',
    messagingSenderId: '7816793803',
    projectId: 'ecommerce-e354a',
    authDomain: 'ecommerce-e354a.firebaseapp.com',
    storageBucket: 'ecommerce-e354a.firebasestorage.app',
    measurementId: 'G-XGJQM28GJN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDedcEkLjjR5ekxa7159p8F-SW_rLClZnk',
    appId: '1:7816793803:android:a40ad88341b324efc1954e',
    messagingSenderId: '7816793803',
    projectId: 'ecommerce-e354a',
    storageBucket: 'ecommerce-e354a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJNWfxvPWREMX1q-HEaWWnoL1pAQMqfSo',
    appId: '1:7816793803:ios:f78f7be506866acec1954e',
    messagingSenderId: '7816793803',
    projectId: 'ecommerce-e354a',
    storageBucket: 'ecommerce-e354a.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJNWfxvPWREMX1q-HEaWWnoL1pAQMqfSo',
    appId: '1:7816793803:ios:f78f7be506866acec1954e',
    messagingSenderId: '7816793803',
    projectId: 'ecommerce-e354a',
    storageBucket: 'ecommerce-e354a.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkcuq1Sxpw9H4gniCQB07kdhpNi8BjpwU',
    appId: '1:7816793803:web:b16cb74bec9e0bfac1954e',
    messagingSenderId: '7816793803',
    projectId: 'ecommerce-e354a',
    authDomain: 'ecommerce-e354a.firebaseapp.com',
    storageBucket: 'ecommerce-e354a.firebasestorage.app',
    measurementId: 'G-LVRS6BBJJM',
  );
}
